---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - name: i want to install apache2
      apt:
       name: apache2
       state: present
      when: ansible_os_family== "Debian"

    - name: i want to start apache2 webserver on node 
      service:
        name: apache2
        state: started
      when: ansible_os_family== "Debian" 

    - name: i want to install httpd webserver on ansible on amazon nodes
      dnf:
        name: httpd
        state: present
      when: ansible_os_family== "RedHat"

    - name: i want to start httpd webserver
      service:
        name: httpd
        state: started
      when: nsible_os_family== "RedHat"