---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
    - name: i want to install apache2
      apt:
       name: apache2
       state: present
    
    - name: i want to start apache2 webserver on node 
      service:
        name: apache2
        state: started
